apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../operator/namespace.yaml
  - ../keycloak-cr/keycloak.yaml
  - ../network-policies/default-deny.yaml
  - ../network-policies/allow-ingress-and-monitoring.yaml
  - ../ingress/ingress.yaml
