resources:
  - ../operator/namespace.yaml
  - ../secrets-examples/db-secret.yaml
  - ../keycloak-cr/keycloak.yaml
  - ../monitoring/servicemonitor.yaml
  - ../network-policies/default-deny.yaml
  - ../network-policies/allow-ingress-and-monitoring.yaml
  - ../ingress/ingress.yaml
