spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-login-client
            client-secret: change-me
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
server:
  port: 8082
