apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zdmooc/keycloak-enterprise-roadmap-v3.git
    targetRevision: main
    path: gitops/argocd/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
