---
# Auteur : Zidane Djamal
# AVERTISSEMENT : Valeurs encodées en base64 pour usage LOCAL uniquement.
# username: keycloak -> a2V5Y2xvYWs=
# password: keycloak -> a2V5Y2xvYWs=
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak-system
type: Opaque
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak-system
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5hZG1pbg==
