# Auteur : Zidane Djamal
# Description : Inventaire Ansible pour l'environnement de production
# Remplacez les adresses IP par celles de vos serveurs réels.

[keycloak_nodes]
kc-node-01 ansible_host=10.0.1.11
kc-node-02 ansible_host=10.0.1.12

[db_nodes]
db-node-01 ansible_host=10.0.1.20

[keycloak_nodes:vars]
ansible_user=rhel-admin
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
