events {}
http {
  server {
    listen 8080;

    location / {
      auth_request /auth;
      proxy_pass http://upstream_app;
      proxy_set_header X-Auth-User $upstream_http_x_auth_request_user;
      proxy_set_header X-Auth-Email $upstream_http_x_auth_request_email;
    }

    location = /auth {
      internal;
      proxy_pass http://oauth2_proxy:4180/oauth2/auth;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-URI $request_uri;
    }
  }
}
