---
# Auteur : Zidane Djamal
# AVERTISSEMENT : Ce fichier contient des valeurs encodées en base64 pour un usage LOCAL uniquement.
# En production, utilisez HashiCorp Vault, Sealed Secrets ou un External Secrets Operator.
#
# Valeurs encodées :
#   username: keycloak   -> a2V5Y2xvYWs=
#   password: keycloak   -> a2V5Y2xvYWs=
#   admin:    admin      -> YWRtaW4=
#   adminpwd: adminadmin -> YWRtaW5hZG1pbg==

# Secret pour la base de données PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak-system
type: Opaque
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
---
# Secret pour les credentials de l'admin Keycloak
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak-system
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW5hZG1pbg==
