apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak-system
spec:
  instances: 1

  db:
    vendor: postgres
    host: postgresql
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  http:
    httpEnabled: true

  hostname:
    hostname: keycloak.apps-crc.testing

  ingress:
    enabled: true
    className: openshift-default

  proxy:
    headers: xforwarded

  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: "1"
