server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: web-client
            client-secret: change-me
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
