apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../manifests/operator/namespace.yaml
  - ../../../manifests/keycloak-cr/keycloak.yaml
  - ../../../manifests/monitoring/servicemonitor.yaml
  - ../../../manifests/network-policies/default-deny.yaml
  - ../../../manifests/network-policies/allow-ingress-and-monitoring.yaml
  - ../../../manifests/ingress/ingress.yaml
